title: "DReaMS"
description: "Dutch Research and Medical Software"
url: "https://dreams-community.github.io"
baseurl: ""

logo: /assets/images/logo.png
logo_alt: "DReaMS"

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-target-blank

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# collections:
#   pages:
#     output: true
#     permalink: /:path/

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      prev_next: false
      # paginate: false


minimal_mistakes_skin: default